site_name: Управление Информационной Безопасностью
site_description: 'Office of Information Security'
#repo_url: https://git.esu.gsp.local/cyberSecurity/docsite.git
site_dir: public

validation:
  absolute_links: ignore
  unrecognized_links: ignore
  anchors: ignore

# Настройка темы
theme:
  name: material
  custom_dir: overrides                      # Кастомные шаблоны/стили в папке `overrides`
  logo: assets/images/logo.svg               # Логотип в шапке
  favicon: assets/images/logo.png            # Иконка вкладки браузера
  language: ru                               # Локализация интерфейса
  features:
    - navigation.indexes    # Индексирование навигации
    - navigation.instant    # ускорение загрузки (SPA)
    - navigation.instant.progress
    - navigation.tracking   # динамический URL страницы
    - navigation.sections   # Секции в навигации
    - navigation.tabs       # Навигация в виде табов
    - navigation.top
    - navigation.prune
#    - toc.integrate         # Интегрировать оглавление страницы в навигацию
    - toc.follow            # Автопрокрутка оглавления
    - search.highlight      # Подсветка результатов поиска
    - search.share          # Кнопка поделиться поиском
    - search.suggest        # Подсказки при поиске
    - content.code.copy     # Кнопка "копировать" для блоков кода
  palette:
    - scheme: default # Светлая тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Переключиться на темную тему
    - scheme: slate # Темная тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлую тему
  font:
    text: Roboto
    code: Roboto Mono

# Расширения для Markdown
markdown_extensions:
  - abbr                    # Сокращения (HTML <abbr>)
  - admonition              # Блоки !!! note, !!! warning
  - attr_list               # Атрибуты HTML ({: .class })
  - def_list                # Списки определений (<dl>)
  - footnotes               # Сноски ([^1])
  - md_in_html              # Markdown внутри HTML-блоков
  - pymdownx.arithmatex:    # Поддержка LaTeX
      generic: true         # Совместимость с MathJax/Katex
  - pymdownx.betterem:      # Умное выделение (**bold**, _italic_)
      smart_enable: all
  - pymdownx.caret          # Вставка символов (^sup^)
  - pymdownx.details        # Сворачиваемые блоки
  - pymdownx.emoji:       # Эмодзи
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   # SVG-генератор
      emoji_index: !!python/name:material.extensions.emoji.twemoji      # Библиотека Twemoji
  - pymdownx.highlight:           # Подсветка кода
      line_spans: __span          # CSS-классы для строк
      pygments_lang_class: true   # Классы языков
  - pymdownx.inlinehilite         # Подсветка в строке (`code`)
  - pymdownx.mark                 #==Выделение текста==
  - pymdownx.tilde                # ~~Зачеркивание~~
  - pymdownx.smartsymbols         # Поддержка (c) → ©, (tm) → ™
  - smarty # двойные дефисы в короткое тире (en dash), а тройные — в длинное (em dash), нормализует кавычки
#  - pymdownx.snippets:  # Вставка указанных файлов в конец каждой страницы
#      auto_append:
#        - includes/mkdocs.md  # Путь относительно папки `docs/`
  - pymdownx.superfences:    # Расширенные блоки кода
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:              # Вкладки
      alternate_style: true       # Альтернативный стиль
      combine_header_slug: true   # Генерация slug для заголовков
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:  # Чекбоксы
      custom_checkbox: true  # Кастомные CSS-классы


plugins:
  - privacy:
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            show_bases: false
            show_source: true
            show_labels: false
            show_root_heading: true
  - redirects:
      redirect_maps:
        'index.md': 'ism/home.md'
  - git-revision-date-localized:
      enable_creation_date: false
  - minify:                           # Минификация HTML
      minify_html: true
  - exporter:
      buttons:
        - title: Просмотреть в PDF
          icon: material-file-move-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
        - title: Скачать в PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          explicit: true # указатель печати явно определенных страниц
          concurrency: 16 # одновременная генерация до 16 PDF-документов
          launch_options:
            args: ["--single-process"]  # Важно для Docker
          browser:
            timeout: 120000 # отключение таймаута, чтоб mkdocs не падал в ошибку при генерации больших PDF
          stylesheets:
            - resources_to_PDF/stylesheets/pdf.scss
          covers:
            front: resources_to_PDF/covers/front.html.j2
            back: resources_to_PDF/covers/back.html.j2
          aggregator:
            enabled: false
            output: all_documentation.pdf
            covers: all
  - search:
      lang: 
        - en
        - ru
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'  # Правила разбиения слов
#      indexing: 'full' # построение поискового индекса !!!! странно но пишет что не поддерживаемая функция
  - awesome-pages
  - macros:
      include_dir: snippets # Для одинаковых фрагментов документов


# Секция для мультиязычности
extra:
  generator: false
#  alternate:
#    - name: English # Название в переключателе
#      link: /en/      # Ссылка на английскую версию
#      lang: en       # Код языка
#    - name: Русский
#      link: ./       # Ссылка на текущую (Русскую) версию
#      lang: ru
  unit:               # глобальные переменные для титульных листов PDF
    brand: 'АО&nbsp;"Газпром шельфпроект"' 
    department: 'Управление информационной безопасности'
#  social:            # Кнопка в футере
#    - name: GitHub
#      icon: fontawesome/brands/github
#      link: https://git.esu.gsp.local/cyberSecurity/docsite


extra_css:
  - assets/stylesheets/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css 

extra_javascript:
#  - assets/scripts/katex.js
#  - assets/scripts/mathjax.js
  - assets/scripts/mkdocs-exporter.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.9.0/mermaid.min.js


copyright: Отдел информационной безопасности &copy; 2023-2025